"""add unique constraint to player_stats.player_id

Revision ID: 1c18f93b7afd
Revises: aa89cb487e48
Create Date: 2026-07-28 11:56:37.590820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c18f93b7afd'
down_revision: Union[str, Sequence[str], None] = 'aa89cb487e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_player_stats_player_id', 'player_stats', ['player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_stats_player_id', 'player_stats', type_='unique')
    # ### end Alembic commands ###
