"""baseline existing schema

Revision ID: aa89cb487e48
Revises:
Create Date: 2026-07-28 11:50:22.637828

Originally autogenerated against a dev DB that already had these tables
(created by an earlier Base.metadata.create_all() call, see DECISIONS.md
Day 2), so Alembic saw no diff and emitted an empty upgrade()/downgrade().
That's a silent no-op on a genuinely fresh database — the next migration
(1c18f93b7afd) then fails with UndefinedTable because `player_stats` was
never created. Replaced with the actual CREATE TABLE statements for
`players` and `player_stats` as they existed at this point (pre unique
constraint, which the next migration still adds).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa89cb487e48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "players",
        sa.Column("player_id", sa.Integer(), primary_key=True),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("long_name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("dob", sa.String(), nullable=True),
        sa.Column("nationality_name", sa.String(), nullable=True),
        sa.Column("preferred_foot", sa.String(), nullable=True),
        sa.Column("primary_position", sa.String(), nullable=True),
        sa.Column("all_positions", sa.String(), nullable=True),
        sa.Column("club_name", sa.String(), nullable=True),
        sa.Column("league_name", sa.String(), nullable=True),
        sa.Column("league_level", sa.Integer(), nullable=True),
        sa.Column("club_contract_valid_until_year", sa.Integer(), nullable=True),
        sa.Column("value_eur", sa.Float(), nullable=True),
        sa.Column("wage_eur", sa.Float(), nullable=True),
        sa.Column("release_clause_eur", sa.Float(), nullable=True),
    )

    op.create_table(
        "player_stats",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("player_id", sa.Integer(), sa.ForeignKey("players.player_id"), nullable=True),
        sa.Column("overall", sa.Integer(), nullable=True),
        sa.Column("potential", sa.Integer(), nullable=True),
        sa.Column("pace", sa.Float(), nullable=True),
        sa.Column("shooting", sa.Float(), nullable=True),
        sa.Column("passing", sa.Float(), nullable=True),
        sa.Column("dribbling", sa.Float(), nullable=True),
        sa.Column("defending", sa.Float(), nullable=True),
        sa.Column("physic", sa.Float(), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("player_stats")
    op.drop_table("players")
